const Icons = {
  insta: require('../assets/icons/insta.png'),
  facebook: require('../assets/icons/facebook.png'),
  youtube: require('../assets/icons/youtube.png'),
  Arrow_drop_up: require('../assets/icons/Arrow_drop_up.png'),
  Arrow_drop_up_gray: require('../assets/icons/Arrow_drop_up_gray.png'),
  document_upload: require('../assets/icons/document_upload.png'),
  home: require('../assets/icons/home.png'),
  home_fill: require('../assets/icons/home_fill.png'),
  squre: require('../assets/icons/squre.png'),
  notification: require('../assets/icons/notification.png'),
  user: require('../assets/icons/user.png'),
  edit: require('../assets/icons/edit.png'),
  languagesquare: require('../assets/icons/languagesquare.png'),
  location: require('../assets/icons/location.png'),
  arrowleft: require('../assets/icons/arrowleft.png'),
  images: require('../assets/icons/images.png'),
  minus: require('../assets/icons/minus.png'),
  plus: require('../assets/icons/plus.png'),
  line: require('../assets/icons/line.png'),
  call: require('../assets/icons/call.png'),
  circle:require('../assets/icons/circle.png'),
  File_dock_fill:require('../assets/icons/File_dock_fill.png'),
  send:require('../assets/icons/send.png'),
  emojihappy:require('../assets/icons/emojihappy.png'),
  play:require('../assets/icons/play.png'),
  inf: require('../assets/icons/inf.png'),
  document_upload_grey: require('../assets/icons/document_upload_grey.png'),
  documentupload: require('../assets/icons/document-upload.png'),
  active: require('../assets/icons/active.png'),
  arrow_right: require('../assets/icons/arrow_right.png'),
  arrow_down: require('../assets/icons/arrow_down.png'),
  lineborder: require('../assets/icons/lineborder.png'),
  Rectangle: require('../assets/icons/Rectangle.png'),
  closefilter: require('../assets/icons/closefilter.png'),
  copy: require('../assets/icons/copy.png'),
  rectanglewhite:require('../assets/images/rectanglewhite.png'),
  document_upload_green: require('../assets/icons/document_upload_green.png'),
  images2: require('../assets/icons/images2.png'),
  imagesGrey: require('../assets/icons/imageGrey.png'),
  activeGrey: require('../assets/icons/activeGrey.png'),
  active2: require('../assets/icons/active2.png'),
  active2Grey: require('../assets/icons/active2Grey.png'),
  active5: require('../assets/icons/active5.png'),
  active6: require('../assets/icons/active6.png'),

  active3: require('../assets/icons/active3.png'),
  active4: require('../assets/icons/active4.png'),
  radio_uncheck: require('../assets/icons/radio_uncheck.png'),
  radiocheck:require('../assets/icons/radio_check.png'),
  useracc: require('../assets/icons/useracc.png'),
  notificationacc: require('../assets/icons/notificationacc.png'),
  elementacc: require('../assets/icons/elementacc.png'),
  documentuploadacc: require('../assets/icons/documentuploadacc.png'),
  ActiveInprogress: require('../assets/icons/ActiveInprogress.png'),
  filter: require('../assets/icons/filter.png'),
  close: require('../assets/icons/close.png'),
  image1: require('../assets/icons/image1.png'),
  reload: require('../assets/icons/reload.jpg'),
  success: require('../assets/icons/green.png'),
  drop_arrow: require('../assets/icons/drop_arrow.png'),
  drop_up: require('../assets/icons/drop_up.png'),
  // sendicon: require('../assets/icons/sendicon.png'),
  sendfile: require('../assets/icons/selectedDoc.png'),
  tick: require('../assets/icons/tick.png'),
  warning: require('../assets/icons/warning.png'),
  warning2: require('../assets/icons/warning2.png'),
  forward: require('../assets/icons/forward.png'),
  profile: require('../assets/icons/profile.png'),
  barter: require('../assets/icons/barter.png'),
  collab: require('../assets/icons/collab.png'),
  chat: require('../assets/icons/chat.png'),
  logoCeleb: require('../assets/icons/LogoCelebFarm.png'),
  add: require('../assets/icons/add.png'),
  back: require('../assets/icons/back.png'),
  profileEdit: require('../assets/icons/profileEdit.png'),
  closeProfileEdit: require('../assets/icons/cross.png'),
  verifytick: require('../assets/icons/verifytick.png'),
  tickGreen: require('../assets/icons/tickGreen.png'),
  Productsoffers_fill: require('../assets/icons/Productsoffers_fill.png'),
  MyCollabs_fill: require('../assets/icons/MyCollabs_fill.png'),
  Profile_fill: require('../assets/icons/Profile_fill.png'),
  arrow: require('../assets/icons/arrow.png'),
  review: require('../assets/icons/review.png'),
  close_barter: require('../assets/icons/close_barter.png'),
  // privacy_policy: require('../assets/icons/privacy_policy.png'),

};

export default Icons;
