name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository so the workflow can access your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js using the official action; this also caches your npm modules
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      # Install dependencies using npm; npm ci is recommended for clean, reproducible installs
      - name: Install dependencies
        run: npm ci

      # Run your tests as defined in your package.json file
      - name: Run tests
        run: npm test

      # Build your project (adjust this command if your build script is named differently)
      - name: Build project
        run: npm run build
